version: "3.8"

services:

  db:
    image: postgres:15-alpine
    container_name: vetclinic-db
    environment:
      POSTGRES_DB: vetdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api:
    build: .
    container_name: vetclinic-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vetdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: always

volumes:
  postgres_data: